<section class="oszlop">
    <?php
    
        Application_Model_DbTable_Articles::showArticlebox($this->articles, "Fotográfia", true);
        Application_Model_DbTable_Articles::showArticlebox($this->articles, "Tutoriálok");
    
    ?>
</section>
<section class="oszlop">
    <?php
    
        Application_Model_DbTable_Articles::showArticlebox($this->articles, "Informatika");
    
    ?>
</section>
<section class="oszlop">
    <?php
    
        Application_Model_DbTable_Articles::showArticlebox($this->articles, "Mobileszközök");
    
    ?>
</section>