<div style="width: 100%; text-align: center;">
    <h2>Sikeresen regisztráltál!</h2>
    Nézd meg az e-mail fiókodat, mert hamarosan kapni fogsz egy levelet az adataiddal és egy hitelesítő linkkel. <br>
    Regisztrációd csak ezen kattintva válik teljessé, és csak azután fogsz tudni belépni!<br><br>
    Ha a levél pár percen belül nem érkezik meg, akkor kérlek nézd meg a SPAM-eket is, mielőtt felvennéd velünk a kapcsolatot!
</div>