<table style='width: 100%; background: white;' border='1px' cellpadding='5px' cellspacing='0'>
    <tr style="font-weight: bold;">
	<td></td>
	<td>Cím</td>
	<td>Cikk id-k</td>
	<td>Státusz</td>
    </tr>
    
<?php
foreach ($this->nls as $nl) {
    echo "<tr>";
    echo "<td>".$nl["id"]."</td>";
    echo "<td><a href='/edit-nl/".$nl["id"]."'>".$nl["title"]."</td>";
    echo "<td>".$nl["articles"]."</td>";

    switch ($nl["status"]) {
	case 0: $status = "Még nem lett kiküldve"; break;
	case 1: $status = "Kiküldve"; break;
    }

    echo "<td>".$status."</td>";
    echo "</tr>";
}

?>

</table>

