<table style='width: 100%; background: white;' border='1px' cellpadding='5px' cellspacing='0'>
    <tr style="font-weight: bold;">
	<td></td>
	<td>Cím</td>
	<td>Fájlnév</td>
    </tr>
    
<?php
foreach ($this->nls as $nl) {
    echo "<tr>";
    echo "<td>".$nl["id"]."</td>";
    echo "<td><a href='/edit_nl/".$nl["id"]."'>".$nl["title"]."</td>";
    echo "<td>".$nl["filename"]."</td>";
    echo "</tr>";
}

?>

</table>

